---
- name: Build petclinic app
  hosts: localhost
  become: yes

  tasks:
  - name: Build docker image
    command: docker build -t 10.0.10.184:5000/mypetclinic .

  - name: Pull pet-clinic application container
    command: docker pull 10.0.10.184:5000/mypetclinic
