---
- name: Run pet-clinic application
  hosts: qa_env
  become: yes

  tasks:

  - name: Pull pet-clinic application container
    command: docker pull -rm -d -p 8080:8080 10.0.10.184:5000/mypetclinic
    
  - name: Run pet-clinic application container
    command: docker pull -rm -d -p 8080:8080 10.0.10.184:5000/mypetclinic
