---
- name: Run pet-clinic application
  hosts: qa_env
  become: yes

  tasks:

  - name: Run pet-clinic application container
    docker_container:
      name: hello
      image: hello-world
      state: present
      restart: true
      ports:
        - "8080:8080"
