apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypetclinic-app
  template:
    metadata:
      labels:
        app: mypetclinic-app
    spec:
      containers:
      - name: mypetclinic-app
        image: 10.0.11.150:5000/mypetclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085

# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mypetclinic-app-svc
spec:
  selector:
    app: mypetclinic-app-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
