---
- name: Run pet-clinic application
  hosts: servers_env
  become: yes

  tasks:
  - name: Ensure that no container is running
    command: docker rm -f staging_mypetclinic || true  

  - name: Pull pet-clinic application container
    command: docker pull 10.0.11.150:5000/mypetclinic:latest
    
  - name: Run pet-clinic application container
    command: docker run --name staging_mypetclinic --rm -d -p 8082:8080 10.0.11.150:5000/mypetclinic:latest
