apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypetclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypetclinic-app
  template:
    metadata:
      labels:
        app: mypetclinic-app
    spec:
      containers:
      - name: mypetclinic-app
        image: httpd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mypetclinic-app-svc
spec:
  selector:
    app: mypetclinic-app-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
